// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { drwebBlock } from "./index";

export const drwebBlockSchema = parseBlockSchema(drwebBlock);
export const drwebCredentialsSchema = parseBlockCredentials(
  drwebBlock.id,
  auth,
);
