// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { smartchatBlock } from "./index";

export const smartchatBlockSchema = parseBlockSchema(smartchatBlock);
export const smartchatCredentialsSchema = parseBlockCredentials(
  smartchatBlock.id,
  auth,
);
