// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { auth } from "./auth";
import { clinixBlock } from "./index";

export const clinixBlockSchema = parseBlockSchema(clinixBlock);
export const clinixCredentialsSchema = parseBlockCredentials(
  clinixBlock.id,
  auth,
);
